services:
  stats-server:
    build: ewm-stats-service
    container_name: stats-service-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - EWM_MAIN_SERVICE_URL=http://ewm-server:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stats_db
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats


  stats-db:
    image: postgres:16.1
    ports:
      - "5001:5432"
    volumes:
      - ./volumes/stats/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewm_stats_db
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10


  ewm-service:
    build: ewm-main-service
    container_name: main-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - EWM_STATS_SERVICE_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - SPRING_DATASOURCE_USERNAME=main
      - SPRING_DATASOURCE_PASSWORD=main

  ewm-db:
    container_name: main-DB-container
    image: postgres:16.1
    ports:
      - "5002:5432"
    volumes:
      - ./volumes/main/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewm_main_db
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10


#  keycloak-postgres:
#    image: postgres:${KC_POSTGRES_IMAGE_TAG:-16.1}
#    container_name: ${POSTGRES_CONTAINER_NAME:-postgres}
#    restart: on-failure
#    volumes:
#      - ./volumes/main/postgres-keycloak:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=postgres
#    healthcheck:
#      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
#      interval: 10s
#      timeout: 5s
#      retries: 3
#      start_period: 5s
#    ports:
#      - ${KC_POSTGRES_PORT_MAPPING:-5435}:5432
#    deploy:
#      resources:
#        limits:
#          memory: 256M
#
#  keycloak:
#    image: quay.io/keycloak/keycloak:26.1.4
#    container_name: keycloak
#    command:
#      - start-dev
#      #- start --auto-build --db postgres --hostname-strict-https false --hostname-strict false --proxy edge --http-enabled true --import-realm --spi-user-profile-legacy-user-profile-read-only-attributes *_RES_ACCESS_MODE
#    environment:
#      KC_DB: postgres
#      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/postgres
#      KC_DB_USERNAME: postgres
#      KC_DB_PASSWORD: postgres
#      KC_DB_SCHEMA: public
#      KC_FEATURES: preview
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#    ports:
#      - 8282:8080
#    depends_on:
#      keycloak-postgres:
#        condition: service_healthy
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/realms/master"]
#      start_period: 10s
#      interval: 30s
#      retries: 3
#      timeout: 5s