services:
  stats-server:
    build: ewm-stats-service
    container_name: stats-service-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - EWM_MAIN_SERVICE_URL=http://ewm-server:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stats_db
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats


  stats-db:
    image: postgres:16.1
    ports:
      - "5001:5432"
    volumes:
      - ./volumes/stats/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewm_stats_db
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10


  ewm-service:
    build: ewm-main-service
    container_name: main-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - EWM_STATS_SERVICE_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - SPRING_DATASOURCE_USERNAME=main
      - SPRING_DATASOURCE_PASSWORD=main

  ewm-db:
    container_name: main-DB-container
    image: postgres:16.1
    ports:
      - "5002:5432"
    volumes:
      - ./volumes/main/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewm_main_db
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
