server.port: 9090

spring:
  datasource:
    username: "stats"
    password: "stats"
    url: "jdbc:postgresql://localhost:5001/ewm_stats_db"
    driver-class-name: "org.postgresql.Driver"

  jpa:
    properties:
      hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
    show-sql: false
    hibernate.ddl-auto: none
    properties.hibernate:
      format_sql: true
  sql:
    init.mode: always