CREATE TABLE ewm_prime.users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  email         VARCHAR(64) UNIQUE,
  created       TIMESTAMP   DEFAULT now() NOT NULL,
  updated       TIMESTAMP   DEFAULT now() NOT NULL,
  firstname     VARCHAR(32),
  lastname      VARCHAR(32),
  role          VARCHAR(32),
  admin_confirm BOOLEAN     DEFAULT FALSE NOT NULL,
  flag_delete   BOOLEAN     DEFAULT FALSE NOT NULL
);

CREATE TABLE ewm_prime.categories (
  id            INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  name          VARCHAR(128) UNIQUE
);

CREATE TABLE ewm_prime.dimension_integer_3 (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  length        INT,
  width         INT,
  height        INT
);

CREATE TABLE ewm_prime.products (
  uuid          UUID        DEFAULT uuid_generate_v4() PRIMARY KEY,
  name          VARCHAR(64),
  description   VARCHAR(2056),
  cost          NUMERIC(20, 2),
  owner_id      BIGINT      NOT NULL REFERENCES ewm_prime.users(id) ON DELETE CASCADE,
  renter_id     BIGINT      REFERENCES ewm_prime.users(id) ON DELETE CASCADE,
  dimension_id  BIGINT      REFERENCES ewm_prime.dimension_integer_3(id) ON DELETE CASCADE,
  created_at    TIMESTAMP   DEFAULT now() NOT NULL,
  updated_at    TIMESTAMP   DEFAULT now() NOT NULL
);

CREATE TABLE ewm_prime.ratings (
  uuid          UUID        DEFAULT uuid_generate_v4() PRIMARY KEY,
  quality       SMALLINT,
  price         SMALLINT,
  marketability SMALLINT,
  popularity    SMALLINT,
  owner_rating  SMALLINT,
  created_at    TIMESTAMP   DEFAULT now() NOT NULL,
  product_id    UUID        NOT NULL REFERENCES ewm_prime.products(uuid),
  buyer_id      BIGINT      NOT NULL REFERENCES ewm_prime.users(id)
);


CREATE TABLE ewm_prime.events (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  name              VARCHAR(64),
  brief_description VARCHAR(128),
  full_description  VARCHAR(2056),
  created           TIMESTAMP,
  modified          TIMESTAMP,
  beginning         TIMESTAMP,
  ending            TIMESTAMP,
  category_id       INT         NOT NULL REFERENCES ewm_prime.categories(id) ON DELETE CASCADE,
  creator_id        BIGINT      NOT NULL REFERENCES ewm_prime.users(id) ON DELETE CASCADE
);