CREATE TABLE ewm_prime.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  email VARCHAR(64) UNIQUE,
  created TIMESTAMP DEFAULT now() NOT NULL,
  updated TIMESTAMP DEFAULT now() NOT NULL,
  firstname VARCHAR(32),
  lastname VARCHAR(32),
  role VARCHAR(32)
);

CREATE TABLE ewm_prime.categories (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  name VARCHAR(128) UNIQUE
);

CREATE TABLE ewm_prime.events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  name VARCHAR(64),
  brief_description VARCHAR(128),
  full_description VARCHAR(2056),
  created TIMESTAMP,
  modified TIMESTAMP,
  beginning TIMESTAMP,
  ending TIMESTAMP,
  category_id INT NOT NULL REFERENCES ewm_prime.categories(id) ON DELETE CASCADE,
  creator_id BIGINT NOT NULL REFERENCES ewm_prime.users(id) ON DELETE CASCADE
);